### PR TITLE
Add Github code scanning workflow

### PR DESCRIPTION
**Pull request by jelly**
This makes ostree 100% green \o/

### CODE REVIEW

**Comment by martinpitt** [comment]
LGTM, thanks! That [pixel failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-333-20230216-115104-bf813a3d-fedora-coreos/log.html) is very odd, though -- it can't possibly that duplicated `rel=`, can it? Retrying once for comparison, this could also just be a random flake -- but I've never seen the ostree tests flake like that.

**Comment by jelly** [comment]
It moved again! This is really interesting!

**Comment by martinpitt** [comment]
@jelly : But at first sight it seems stable between the two runs? Want to just update it and confirm that it's stable?

**Comment by jelly** [comment]
> @jelly : But at first sight it seems stable between the two runs? Want to just update it and confirm that it's stable?

Soo... the pixel tests was not rebased! *SHOCK*

**Review by martinpitt — APPROVED** [review]
Nice!

**Pull request merged**
