### PR TITLE
Add translations

### PR DESCRIPTION
**Pull request by marusak**
I did demo run on my forks:
Updated source: https://github.com/marusak/cockpit-ostree-weblate/commit/562b455de0699369c38ffece84bedd3cf5a597d8
Pull request: https://github.com/marusak/cockpit-ostree/pull/1

We don't have yet Weblate project as I don't have permissions to create one. But I sent request for it.

 * [x] po-refresh

(p.s. We don't have no-test label) EDIT: We do now :)

### CODE REVIEW

**Comment by cockpituous** [comment]
po-refresh in progress on 1-ci-srv-03.
Log: https://209.132.184.41:8493/logs/po-refresh-43-20200131-092424/

**Comment by cockpituous** [comment]
cockpituous doesn't have a fork of cockpit-project/cockpit-ostree: https://209.132.184.41:8493/logs/po-refresh-43-20200131-092424/

**Comment by marusak** [comment]
> cockpituous doesn't have a fork of cockpit-project/cockpit-ostree: https://209.132.184.41:8493/logs/po-refresh-43-20200131-092424/

:)
@Gundersanne or @martinpitt can you please give bots a fork :)

**Comment by martinpitt** [comment]
Done: 🤖 🍴

(shame.. no unicode symbol for a single fork??)

**Comment by cockpituous** [comment]
po-refresh in progress on 4-cockpit-7.
Log: https://209.132.184.41:8493/logs/po-refresh-43-20200131-095454/

**Comment by cockpituous** [comment]
po-refresh  done: https://github.com/cockpituous/cockpit-ostree/commits/po-refresh-20200131-095454

**Comment by martinpitt** [comment]
@marusak: Seems to work fine, thanks! (Well, it just deletes incomplete translations, but I suppose that's right). I'll do some German translations in weblate.

Can you please add a Closes #? Then I'll approve.

**Comment by marusak** [comment]
> @marusak: Seems to work fine, thanks! (Well, it just deletes incomplete translations, but I suppose that's right). I'll do some German translations in weblate.

Yeah, it does, but that is what we expect from it. I added Slovak, so it should be picked up as a new language. And if you would translate at least one word in German, that would be great (to validate that it is picked up correctly).

> Can you please add a Closes #? Then I'll approve.

I planed to pick up also this po-refresh, but let's do another one where also would be a new language and update in some existing.

**Comment by martinpitt** [comment]
@marusak : I translated most strings in weblate now. I skipped some, like those that contain "deployment", as I have no good idea how to translate that :)

**Pull request merged**
