### PR TITLE
Move page status icons to PF4

### LINKED ISSUE #226: Health card icon is missing
The icon is missing on the overview page when cockpit-ostree is installed:

Screenshot 2022-01-31 at 18-40-24 Overview - garrett Bolt

### PR DESCRIPTION
**Pull request by marusak**
Move away from the PF3 FontAwesome names in favor of the PF4 icon components.

See https://github.com/cockpit-project/cockpit/commit/85fd223bfc261826cb4c607efb6ef38f11609b47

Fixes #226

### CODE REVIEW

**Review by martinpitt — CHANGES_REQUESTED** [review]
I can confirm the bug and the fix, thank you! Do you want to adjust the test case yourself, or want me to?

**Comment by marusak** [comment]
>  Do you want to adjust the test case yourself, or want me to?

On it. I was looking at those tests and thought it will be fine, but indeed, `<span>` is not present in PF4 icons anymore, it is `<svg>`

**Review by martinpitt — APPROVED** [review]
Cheers!

**Review by garrett — COMMENTED** [review]
The icon is weird:

Screenshot 2022-02-01 at 09-27-44 Overview - garrett Bolt

Spinner is also odd and so is the spacing:

Screenshot from 2022-02-01 09-29-56

**Comment by garrett** [comment]
Ugh, I missed the review window. I guess this needs a follow-up.

**Pull request merged**
