### PR TITLE
Cleanup tests

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Great! Bots have the final word of course.

**Comment by jelly** [comment]
> Great! Bots have the final word of course.

The subscription manager one raised the most doubts for me, but it seems to go green with plenty of retries!

**Comment by martinpitt** [comment]
Uh, plenty of retries? That is highly suspicious! There have been [no know flakes](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit-ostree) in the last two weeks. Do you mean you retried failed tests, or you force-retried passing tests for extra validation, or you just referred to the automatic "3x affected" retries?

**Comment by jelly** [comment]
> Uh, plenty of retries? That is highly suspicious! There have been [no known flakes](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit-ostree) in the last two weeks. Do you mean you retried failed tests, or you force-retried passing tests for extra validation, or you just referred to the automatic "3x affected" retries?

Yes, the latter the affected retries!

**Pull request merged**
