### PR TITLE
Enable copr builds for packit config

### PR DESCRIPTION
**Pull request by dhodovsk**
We enabled copr builds in the packit config for you.

After merging this PR, you are just a few steps away from RPM builds being automatically triggered on your PR's.
It means, that you'll be able to try and play with your change, packaged as an RPM.

What are the next steps?
* Install [Packit-as-a-Service github application](https://github.com/marketplace/packit-as-a-service) in your repo
* In case you are first user, wait for account approval
* Enjoy the built RPMs!

For more info, please:
 * check out the documentation: https://packit.dev/docs/
 * contact [@packit-service/the-packit-team](https://github.com/orgs/packit-service/teams/the-packit-team)

### CODE REVIEW

**Comment by martinpitt** [comment]
@dhodovsk : I'm terribly sorry that we have ignored this for so long :crying_cat_face: . The thing is, this wouldn't really give us anything for this project in particular -- The copr build doesn't run *any* unit test, and the build itself is utterly trivial, basically just a single `cp -r`. The build happens as part of our downstream integration tests, which then also runs the actual browser tests.

However, I now learned about packit github upstream in general, e.g. [here](https://github.com/martinpitt/python-simpleline/pull/1), and we are also [enabling it officially](https://github.com/rhinstaller/python-simpleline/pull/83) for a project where it makes sense, and I also [gave some feedback](https://github.com/packit/packit-service/issues/859#issuecomment-725963676).

I still have it on my TODO list to use packit for *releasing* cockpit-ostree -- The [bug that blocked us](https://github.com/packit/packit/issues/427) for 1½ years finally got resolved two weeks ago :tada: , so it's time to try this again. That'll look totally different, thus I'll send a separate PR for that.

Thank you!

**Comment by martinpitt** [comment]
I changed my mind -- I forgot the already existing packit config file, and the simplifications are nice. Having this build will provide some initial validation for the packit release build, and we can still disable the `pull_request` trigger later. However, I changed it to run on rawhide only.

I enabled packit for the cockpit-project org and this repo, and force-push to trigger it.

**Comment by martinpitt** [comment]
@dhodovsk , @thrix : Hm, this [failed badly](https://prod.packit.dev/srpm-build/10054/logs):
```
env -u NODE_ENV npm install
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1021440000:0 "/.npm"
```
Seems the nodes you are running this on have some unclean builder home directory?

**Comment by thrix** [comment]
@martinpitt no idea, seems this is packit side (not testing farm) summoning @ttomecek @lachmanfrantisek

**Comment by lachmanfrantisek** [comment]
@thrix @martinpitt Thanks for letting us know. I've created an issue on our side (https://github.com/packit/sandcastle/issues/85). I've proposed rebuilding the sandbox image. Looking at the proposed command, it can be related to the (random) user that run's the command in openshift.

**Comment by martinpitt** [comment]
/packit build

Trying again, we got some successful packit builds in rhinstaller today.

**Comment by jpopelka** [comment]
https://github.com/packit/sandcastle/issues/85 has been fixed and is currently deployed only in the staging instance of packit-service.
It will be deployed to production next week, i.e. Mon Dec 21

**Comment by martinpitt** [comment]
packit made a lot of progress in the recent weeks, and is settling down now. I finally managed to get the srpm builds to work in PR #172, so I guess it's *finally* time to enable this :grin: 

I rebased your PR to current master. We previously used to have packit builds for all Fedora releases, but indeed it is totally fine to only have rawhide -- the RPMs will work on any Fedora, they are noarch and are only very loosely coupled to cockpit.

**Comment by TomasTomecek** [comment]
one note, Dominika is no longer on our team (she's partying with OSCI now :)

**Comment by martinpitt** [comment]
@TomasTomecek : Right, but I still want to salvage her PR. It works great now, so I'll land this (once our own tests succeed). Thank you!

**Comment by martinpitt** [comment]
That's also all that we can do with packit on c-ostree. Running tests doesn't work as that needs a Fedora OSTree testbed, not a classic Fedora one. But we'll do the tests bits with cockpit and cockpit-podman.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
