### PR TITLE
package.json: Update moment package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
npm-update in progress on centosci-tasks-p9rqh.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/npm-update-152-20201009-112424/

**Comment by cockpituous** [comment]
npm-update moment done: https://github.com/cockpituous/cockpit-ostree/commits/npm-update-moment-20201009-112525

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "moment": "2.29.1",
src/app.jsx:import moment from 'moment';
src/app.jsx:            <label className="control-label" htmlFor="osrelease">{ _("Released") }</label> <div className="timestamp" id="osrelease">{moment.unix(info.timestamp.v).fromNow()}</div>
```

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "moment": "2.29.1",
src/app.jsx:import moment from 'moment';
src/app.jsx:            <label className="control-label" htmlFor="osrelease">{ _("Released") }</label> <div className="timestamp" id="osrelease">{moment.unix(info.timestamp.v).fromNow()}</div>
```

**Review by marusak — APPROVED** [review]

**Pull request merged**
